version: 2
jobs:
  build:
    docker:
      - image: circleci/node:dubnium
        environment:
        - NODE_ENV: testing
    environment:
      TERM: xterm-256color
    working_directory: ~/soc-frontend

    steps:
      - checkout

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Run application unit tests
          command: yarn coverage
      - run:
          name: Collect test coverage
          command: yarn coveralls
  deploy:
    docker:
      - image: circleci/node:dubnium
    environment:
      TERM: xterm-256color
    working_directory: ~/soc-frontend

    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
          
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build and release application
          command: |
            chmod +x scripts/deploy.sh && scripts/deploy.sh
      - run:
          name: Build Success
          when: on_success
          command: |
            if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
                bash scripts/slack_notification.sh "success"
            fi
      - run:
          name: Build Failed
          when: on_fail
          command: |
            if [ "$CIRCLE_NODE_INDEX" == 0 ]; then
                bash scripts/slack_notification.sh "fail"
            fi

workflows:
  version: 2
  build-test-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - develop-V2
                - master-V2
